services:
  api:
    image: melodimancer-r-api
    container_name: r-api
    build: .
    ports:
      - '8000:8000'
    develop:
      watch:
        - action: sync+restart
          path: api_definition.R
          target: ./api_definition.R